// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCLp4GCuf1sd-6opplz5uAwczZ8N6q1M',
    appId: '1:716697416914:web:d8304a0c67ea9bf86d690b',
    messagingSenderId: '716697416914',
    projectId: 'snapdream2920',
    authDomain: 'snapdream2920.firebaseapp.com',
    storageBucket: 'snapdream2920.firebasestorage.app',
    measurementId: 'G-614BYC1NJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmKSki9W71BsbV6xiPrOjkGsJysSF7mOk',
    appId: '1:716697416914:android:5905c65c6b7d5c106d690b',
    messagingSenderId: '716697416914',
    projectId: 'snapdream2920',
    storageBucket: 'snapdream2920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQfZhSXeVyIL_lUU4Qlw-XqlAbK2AUbzM',
    appId: '1:716697416914:ios:475f857e381085b86d690b',
    messagingSenderId: '716697416914',
    projectId: 'snapdream2920',
    storageBucket: 'snapdream2920.firebasestorage.app',
    iosBundleId: 'com.example.snapdreamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQfZhSXeVyIL_lUU4Qlw-XqlAbK2AUbzM',
    appId: '1:716697416914:ios:475f857e381085b86d690b',
    messagingSenderId: '716697416914',
    projectId: 'snapdream2920',
    storageBucket: 'snapdream2920.firebasestorage.app',
    iosBundleId: 'com.example.snapdreamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFCLp4GCuf1sd-6opplz5uAwczZ8N6q1M',
    appId: '1:716697416914:web:70e488491b1937a36d690b',
    messagingSenderId: '716697416914',
    projectId: 'snapdream2920',
    authDomain: 'snapdream2920.firebaseapp.com',
    storageBucket: 'snapdream2920.firebasestorage.app',
    measurementId: 'G-6S92T5BVZ7',
  );
}
